rm Y*
rm 100btc.kiev.uarequest-exportxml.xml?lang=ru
rm 1-online.rurequest-exportxml.xml?lang=ru
rm 1wm.kzexportxml.xml
rm 24bestex.comrequest-exportxml.xml?lang=ru
rm 24-exchange.comexportxml.xml
rm 24obmen.orgrates.xml
rm 24pay.meexport_rates.xml
rm alypal.comexportxml.xml
rm api.bestcoin.ccxratesexportbestchange
rm api.ecashme.comruexportxml
rm api.my-xchange.comexportxml
rm badX100btc.kiev.uaXrequest-exportxml.xml?lang=ru
rm badX1-online.ruXrequest-exportxml.xml?lang=ru
rm badX1wm.kzXexportxml.xml
rm badX24bestex.comXrequest-exportxml.xml?lang=ru
rm badX24-exchange.comXexportxml.xml
rm badX24obmen.orgXrates.xml
rm badXalypal.comXexportxml.xml
rm badXapi.bestcoin.ccXxratesXexportXbestchange
rm badXapi.ecashme.comXruXexportXxml
rm badXapi.my-xchange.comXexportXxml
rm badXbestobmin.netXrates.html?sType=estandarts_xml
rm badXchangemoney24.ruXrequest-exportxml.xml
rm badXchby.ruXrequest-exportxml.xml?lang=ru
rm badXeasy-changer.ruXrequest-exportxml.xml?lang=ru
rm badXechange.suXexportxml.xml
rm badXe-dengi.orgXrates.html?sType=estandarts_xml
rm badXe-money.ccXrates.html?sType=estandarts_xml
rm badXe-obmen.netXexport.php
rm badXexcash.netXrequest-exportxml.xml
rm badXexchangecity.ruXexportXrates_city.txt
rm badXexchangerwm.comXresXxmlXexprates.xml
rm badXex-code.ruXrequest-exportxml.xml
rm badXexpayer.ruXpartnerXexport.xml
rm badXexwp.orgXestandardsXkurs.xml
rm badXf-change.bizXfchange_courses.xml
rm badXfenix-pay.comXcurs
rm badXi-obmen.bizXexportxml.xml
rm badXmagneticexchange.comXexport.xml
rm badXm-obmen.ruXruXexportXxml
rm badXobmen.ccXrates.xml
rm badXobmenka24.ru
rm badXobmenka.biz.uaXexportxml.xml
rm badXobmenka.uaXexchange-rates-xml
rm badXobmennik.ruXestandardxmlX?pid=163
rm badXobmennik.uaXruXexportXxml
rm badXobmennik.wsXruXexportXxml
rm badXobmenom.comXrates.xml
rm badXonlinechange.comXXEstandardsXUT?pid=12376&code=ESTDRT_FULL
rm badXpayeer.comXxmlXexport.xml
rm badXpm-obmen.tvXexportxml.xml
rm badXrapid-obmen.comXexportxml.xml
rm badXrates.exchangex.ruXexported_rates.php?format=2
rm badXsimplypay.orgXruXcustomXexport2
rm badXsmartwm.ruX
rm badXsuperchange.isXexport.php?type=1
rm badXsuperobmenka.comXruXexportXxml
rm badXultrachange24.comXrates.html?sType=estandarts_xml
rm badXvmex.infoXexport.php
rm badXv-obmen.netXexportxml.xml
rm badXwmalliance.ruXexportFile.xml
rm badXwmbox.com.uaXmonitor_moment.xml
rm badXwmcasher.ruXestandardxmlX?pid=163
rm badXwmchange24.netXexport.xml
rm badXwmchange.in.uaXexport.xml
rm badXwmcurrency.comXexportXmonitorXxml
rm badXwmirk.ruXexport.php?type=csvfl
rm badXwmpaycash.comXruXexportXxml
rm badXwm-privat.comXexport.xml
rm badXwm-sha.ruXexport.xml
rm badXwmt21.infoXexportxml.xml
rm badXwmt24.ruXwm_softXexportXrates.php
rm badXwww.abcash.orgXexport_rates.xml
rm badXwww.alfacashier.comXexchangeXexportXratesXxmlXshort
rm badXwww.changer.comXapiXrates.xml
rm badXwww.demonchange.ruXratesXru.xml
rm badXwww.nixexchange.comXbest.xml
rm badXwww.webobmen.comXcurrent_state_ut.txt
rm badXwww.xmlgold.euXruXrequestXrates
rm badXxchange-24.comXexport2.php?f=xml
rm badXxebit.ru
rm badXz-obmen.ruXrequest-exportxml.xml?lang=ru
rm bestobmin.netrates.html?sType=estandarts_xml
rm changemoney24.rurequest-exportxml.xml
rm chby.rurequest-exportxml.xml?lang=ru
rm easy-changer.rurequest-exportxml.xml?lang=ru
rm easychange.ruexport_xml1.txt
rm echange.suexportxml.xml
rm e-dengi.orgrates.html?sType=estandarts_xml
rm e-money.ccrates.html?sType=estandarts_xml
rm e-obmen.netexport.php
rm excash.netrequest-exportxml.xml
rm exchangecity.ruexportrates_city.txt
rm exchangerwm.comresxmlexprates.xml
rm ex-code.rurequest-exportxml.xml
rm expayer.rupartnerexport.xml
rm exwp.orgestandardskurs.xml
rm f-change.bizfchange_courses.xml
rm fenix-pay.comcurs
rm foo.db
rm i-obmen.bizexportxml.xml
rm magneticexchange.comexport.xml
rm m-obmen.ruruexportxml
rm obmen.ccrates.xml
rm obmenka24.ru
rm obmenka.biz.uaexportxml.xml
rm obmenka.uaexchange-rates-xml
rm obmennik.ruestandardxml?pid=163
rm obmennik.uaruexportxml
rm obmennik.wsruexportxml
rm obmenom.comrates.xml
rm okX100btc.kiev.uaXrequest-exportxml.xml?lang=ru
rm okX1-online.ruXrequest-exportxml.xml?lang=ru
rm okX1wm.kzXexportxml.xml
rm okX24bestex.comXrequest-exportxml.xml?lang=ru
rm okX24-exchange.comXexportxml.xml
rm okX24obmen.orgXrates.xml
rm okXalypal.comXexportxml.xml
rm okXapi.bestcoin.ccXxratesXexportXbestchange
rm okXapi.ecashme.comXruXexportXxml
rm okXapi.my-xchange.comXexportXxml
rm okXbestobmin.netXrates.html?sType=estandarts_xml
rm okXchangemoney24.ruXrequest-exportxml.xml
rm okXchby.ruXrequest-exportxml.xml?lang=ru
rm okXeasy-changer.ruXrequest-exportxml.xml?lang=ru
rm okXeasychange.ruXexport_xml1.txt
rm okXechange.suXexportxml.xml
rm okXe-dengi.orgXrates.html?sType=estandarts_xml
rm okXe-obmen.netXexport.php
rm okXexcash.netXrequest-exportxml.xml
rm okXexchangerwm.comXresXxmlXexprates.xml
rm okXex-code.ruXrequest-exportxml.xml
rm okXexpayer.ruXpartnerXexport.xml
rm okXexwp.orgXestandardsXkurs.xml
rm okXf-change.bizXfchange_courses.xml
rm okXfenix-pay.comXcurs
rm okXmagneticexchange.comXexport.xml
rm okXm-obmen.ruXruXexportXxml
rm okXobmen.ccXrates.xml
rm okXobmenka.uaXexchange-rates-xml
rm okXobmennik.ruXestandardxmlX?pid=163
rm okXobmennik.uaXruXexportXxml
rm okXobmennik.wsXruXexportXxml
rm okXobmenom.comXrates.xml
rm okXonlinechange.comXXEstandardsXUT?pid=12376&code=ESTDRT_FULL
rm okXpayeer.comXxmlXexport.xml
rm okXpm-obmen.tvXexportxml.xml
rm okXrapid-obmen.comXexportxml.xml
rm okXrates.exchangex.ruXexported_rates.php?format=2
rm okXsuperchange.isXexport.php?type=1
rm okXsuperobmenka.comXruXexportXxml
rm okXultrachange24.comXrates.html?sType=estandarts_xml
rm okXvmex.infoXexport.php
rm okXv-obmen.netXexportxml.xml
rm okXwmalliance.ruXexportFile.xml
rm okXwmbox.com.uaXmonitor_moment.xml
rm okXwmcasher.ruXestandardxmlX?pid=163
rm okXwmchange24.netXexport.xml
rm okXwmchange.in.uaXexport.xml
rm okXwmcurrency.comXexportXmonitorXxml
rm okXwmpaycash.comXruXexportXxml
rm okXwm-privat.comXexport.xml
rm okXwm-sha.ruXexport.xml
rm okXwmt21.infoXexportxml.xml
rm okXwmt24.ruXwm_softXexportXrates.php
rm okXwww.abcash.orgXexport_rates.xml
rm okXwww.alfacashier.comXexchangeXexportXratesXxmlXshort
rm okXwww.changer.comXapiXrates.xml
rm okXwww.demonchange.ruXratesXru.xml
rm okXwww.nixexchange.comXbest.xml
rm okXwww.xmlgold.euXruXrequestXrates
rm okXxchange-24.comXexport2.php?f=xml
rm okXz-obmen.ruXrequest-exportxml.xml?lang=ru
rm onlinechange.comEstandardsUT?pid=12376&code=ESTDRT_FULL
rm payeer.comxmlexport.xml
rm pm-obmen.tvexportxml.xml
rm rapid-obmen.comexportxml.xml
rm rates.exchangex.ruexported_rates.php?format=2
rm scan10
rm scan10.log
rm scan11
rm scan12
rm scan3
rm scan3.log
rm scan4
rm scan4.log
rm scan5
rm scan5.log
rm scan6
rm scan6.log
rm scan7
rm scan7.log
rm scan8
rm scan8.db
rm scan8.db-shm
rm scan8.log
rm scan9
rm scan.db
rm scanplus1
rm scanplus1.log
rm scanplus2
rm scanplus2.log
rm simplypay.orgrucustomexport2
rm smartwm.ru
rm sqconnect
rm sql2
rm sql3
rm sql4
rm src
rm st1
rm store
rm superchange.isexport.php?type=1
rm superobmenka.comruexportxml
rm ultrachange24.comrates.html?sType=estandarts_xml
rm vmex.infoexport.php
rm v-obmen.netexportxml.xml
rm wmalliance.ruexportFile.xml
rm wmbox.com.uamonitor_moment.xml
rm wmcasher.ruestandardxml?pid=163
rm wmchange24.netexport.xml
rm wmchange.in.uaexport.xml
rm wmcurrency.comexportmonitorxml
rm wmirk.ruexport.php?type=csvfl
rm wmpaycash.comruexportxml
rm wm-privat.comexport.xml
rm wm-sha.ruexport.xml
rm wmt21.infoexportxml.xml
rm wmt24.ruwm_softexportrates.php
rm www.abcash.orgexport_rates.xml
rm www.alfacashier.comexchangeexportratesxmlshort
rm www.changer.comapirates.xml
rm www.demonchange.ruratesru.xml
rm www.nixexchange.combest.xml
rm www.webobmen.comcurrent_state_ut.txt
rm www.xmlgold.eururequestrates
rm X100btc.kiev.uaXrequest-exportxml.xml?lang=ru
rm X1-online.ruXrequest-exportxml.xml?lang=ru
rm X1wm.kzXexportxml.xml
rm X24bestex.comXrequest-exportxml.xml?lang=ru
rm X24-exchange.comXexportxml.xml
rm X24obmen.orgXrates.xml
rm Xalypal.comXexportxml.xml
rm Xapi.bestcoin.ccXxratesXexportXbestchange
rm Xapi.ecashme.comXruXexportXxml
rm Xapi.my-xchange.comXexportXxml
rm Xbestobmin.netXrates.html?sType=estandarts_xml
rm xchange-24.comexport2.php?f=xml
rm Xchangemoney24.ruXrequest-exportxml.xml
rm Xchby.ruXrequest-exportxml.xml?lang=ru
rm Xeasy-changer.ruXrequest-exportxml.xml?lang=ru
rm Xeasychange.ruXexport_xml1.txt
rm xebit.ru
rm Xechange.suXexportxml.xml
rm Xe-dengi.orgXrates.html?sType=estandarts_xml
rm Xe-obmen.netXexport.php
rm Xexcash.netXrequest-exportxml.xml
rm Xexchangerwm.comXresXxmlXexprates.xml
rm Xex-code.ruXrequest-exportxml.xml
rm Xexpayer.ruXpartnerXexport.xml
rm Xexwp.orgXestandardsXkurs.xml
rm Xf-change.bizXfchange_courses.xml
rm Xfenix-pay.comXcurs
rm Xmagneticexchange.comXexport.xml
rm Xm-obmen.ruXruXexportXxml
rm Xobmen.ccXrates.xml
rm Xobmenka.uaXexchange-rates-xml
rm Xobmennik.ruXestandardxmlX?pid=163
rm Xobmennik.uaXruXexportXxml
rm Xobmennik.wsXruXexportXxml
rm Xobmenom.comXrates.xml
rm Xonlinechange.comXXEstandardsXUT?pid=12376&code=ESTDRT_FULL
rm Xpayeer.comXxmlXexport.xml
rm Xpm-obmen.tvXexportxml.xml
rm Xrapid-obmen.comXexportxml.xml
rm Xrates.exchangex.ruXexported_rates.php?format=2
rm Xsuperchange.isXexport.php?type=1
rm Xsuperobmenka.comXruXexportXxml
rm Xultrachange24.comXrates.html?sType=estandarts_xml
rm Xvmex.infoXexport.php
rm Xv-obmen.netXexportxml.xml
rm Xwmalliance.ruXexportFile.xml
rm Xwmbox.com.uaXmonitor_moment.xml
rm Xwmcasher.ruXestandardxmlX?pid=163
rm Xwmchange24.netXexport.xml
rm Xwmchange.in.uaXexport.xml
rm Xwmcurrency.comXexportXmonitorXxml
rm Xwmpaycash.comXruXexportXxml
rm Xwm-privat.comXexport.xml
rm Xwm-sha.ruXexport.xml
rm Xwmt21.infoXexportxml.xml
rm Xwmt24.ruXwm_softXexportXrates.php
rm Xwww.abcash.orgXexport_rates.xml
rm Xwww.alfacashier.comXexchangeXexportXratesXxmlXshort
rm Xwww.changer.comXapiXrates.xml
rm Xwww.demonchange.ruXratesXru.xml
rm Xwww.nixexchange.comXbest.xml
rm Xwww.xmlgold.euXruXrequestXrates
rm Xxchange-24.comXexport2.php?f=xml
rm Xz-obmen.ruXrequest-exportxml.xml?lang=ru
rm Y100btc.kiev.uarequest-exportxml.xml?lang=ru
rm Y1-online.rurequest-exportxml.xml?lang=ru
rm Y1wm.kzexportxml.xml
rm Y24bestex.comrequest-exportxml.xml?lang=ru
rm Y24-exchange.comexportxml.xml
rm Y24obmen.orgrates.xml
rm Yalypal.comexportxml.xml
rm Yapi.bestcoin.ccxratesexportbestchange
rm Yapi.ecashme.comruexportxml
rm Yapi.my-xchange.comexportxml
rm Ybestobmin.netrates.html?sType=estandarts_xml
rm Ychangemoney24.rurequest-exportxml.xml
rm Ychby.rurequest-exportxml.xml?lang=ru
rm Yeasy-changer.rurequest-exportxml.xml?lang=ru
rm Yeasychange.ruexport_xml1.txt
rm Yechange.suexportxml.xml
rm Ye-dengi.orgrates.html?sType=estandarts_xml
rm Ye-money.ccrates.html?sType=estandarts_xml
rm Ye-obmen.netexport.php
rm Yexcash.netrequest-exportxml.xml
rm Yexchangecity.ruexportrates_city.txt
rm Yexchangerwm.comresxmlexprates.xml
rm Yex-code.rurequest-exportxml.xml
rm Yexpayer.rupartnerexport.xml
rm Yexwp.orgestandardskurs.xml
rm Yf-change.bizfchange_courses.xml
rm Yfenix-pay.comcurs
rm Yi-obmen.bizexportxml.xml
rm Ymagneticexchange.comexport.xml
rm Ym-obmen.ruruexportxml
rm Yobmen.ccrates.xml
rm Yobmenka24.ru
rm Yobmenka.biz.uaexportxml.xml
rm Yobmenka.uaexchange-rates-xml
rm Yobmennik.ruestandardxml?pid=163
rm Yobmennik.uaruexportxml
rm Yobmennik.wsruexportxml
rm Yobmenom.comrates.xml
rm Yonlinechange.comEstandardsUT?pid=12376&code=ESTDRT_FULL
rm Ypayeer.comxmlexport.xml
rm Ypm-obmen.tvexportxml.xml
rm Yrapid-obmen.comexportxml.xml
rm Yrates.exchangex.ruexported_rates.php?format=2
rm Ysimplypay.orgrucustomexport2
rm Ysmartwm.ru
rm Ysuperchange.isexport.php?type=1
rm Ysuperobmenka.comruexportxml
rm Yultrachange24.comrates.html?sType=estandarts_xml
rm Yvmex.infoexport.php
rm Yv-obmen.netexportxml.xml
rm Ywmalliance.ruexportFile.xml
rm Ywmbox.com.uamonitor_moment.xml
rm Ywmcasher.ruestandardxml?pid=163
rm Ywmchange24.netexport.xml
rm Ywmchange.in.uaexport.xml
rm Ywmcurrency.comexportmonitorxml
rm Ywmirk.ruexport.php?type=csvfl
rm Ywmpaycash.comruexportxml
rm Ywm-privat.comexport.xml
rm Ywm-sha.ruexport.xml
rm Ywmt21.infoexportxml.xml
rm Ywmt24.ruwm_softexportrates.php
rm Ywww.abcash.orgexport_rates.xml
rm Ywww.alfacashier.comexchangeexportratesxmlshort
rm Ywww.changer.comapirates.xml
rm Ywww.demonchange.ruratesru.xml
rm Ywww.nixexchange.combest.xml
rm Ywww.webobmen.comcurrent_state_ut.txt
rm Ywww.xmlgold.eururequestrates
rm Yxchange-24.comexport2.php?f=xml
rm Yxebit.ru
rm Yz-obmen.rurequest-exportxml.xml?lang=ru
rm z-obmen.rurequest-exportxml.xml?lang=ru
